name: chal_ostaad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  # Utilities
  http: ^1.6.0
  dart_random_choice: ^0.2.0
  shared_preferences: ^2.5.3
  logger: ^2.6.2
  google_fonts: ^6.3.2
  # Riverpod - Use stable version
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.8
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.7


flutter_native_splash:
  color: "#FB9824"
  android: true
  ios: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/logowb.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/